### ISSUE TITLE
Real time chart

### ISSUE THREAD

**Issue by mokaikai** [knockdata/spark-highcharts#11]
If it possible create real time chart with spark streaming?
Like this:

```
object ChartSingleton {
  private var instance:highcharts = _

  def getInstance(df:DataFrame):highcharts = {
    if (instance == null) {
      instance = highcharts(df
        .seriesCol("Kind")
        .series("x" -> "Time", "y" -> "Count")
        .orderBy(col("Time")))
    } else {
      instance.update(df)
    }
    instance
  }
}

...

// some spark streaming code

lines.foreachRDD { rdd =>
  val df = rdd.map(x=>(x._1._1, x._1._2, x._2)).toDF("Time", "Kind", "Count")
  val chart = ChartSingleton.getInstance(df)
  chart.plot()
}

...
```

**Comment by rockiey** [comment]
the `chart` object does not hold real content. It just used to convert to Javascript. So it is not necessary to keep it. 

It should work, each time plot a new chart. While it will have a flash. 

The `plot` function is designed to be used in Zeppelin. The `html` method is designed to open directly in a browser or create a HTML page.

**Comment by rockiey** [comment]
After some study, I think [Spark Structured Streaming](http://spark.apache.org/docs/latest/structured-streaming-programming-guide.html) is well suited.  

The final interface shall be almost the same with normal DataFrame. It might be finished in a week or two.

For the following structure streaming example.

    import spark.implicits._


    // start netcat with 
    // nc -l -p 9999 127.0.0.1
    // then type in sentence and hit enter
    // there should be something print out on spark-shell

    val lines = (spark.readStream
      .format("socket")
      .option("host", "localhost")
      .option("port", 9999)
      .load())

    // Split the lines into words
    val words = lines.as[String].flatMap(_.split(" "))

    // Generate running word count
    val wordCounts = words.groupBy("value").count()

Create a bar chart, will be update automatically 

    val chart = highcharts(wordCounts
      .series("x" -> name, "y" -> $"count"))
      .orderBy($"count".desc")
      .take(20)).chart(Chart.bar)
    chart.plot()

**Comment by rockiey** [comment]
Implemented in code, will wrap up with documents. 

http://stackoverflow.com/questions/40490087/how-to-plot-a-real-time-graph-in-zeppelin/
