### ISSUE TITLE
Drill Down functionality not working

### ISSUE THREAD

**Issue by HarvinderBhullar** [knockdata/spark-highcharts#15]
Hi
I am trying out the following code on Zeppelin 0.6.1, which is running on Spark 2.0. The chart shows up but  the drill down functionality is not working.

val chart = highcharts(bank
  .series("name" -> "marital",
    "y" -> avg(col("balance")))
  .drilldown("name" -> "job",
    "y" -> avg(col("balance")))
  .drilldown("name" -> "education",
    "y" -> max(col("balance"))))
  .chart(Chart.column)

chart.plot()

**Comment by rockiey** [comment]
How do you setup the environment? Do you build Zeppelin yourself, using zeppelin-highcharts docker image, or add javascript to zeppelin paragraph?

If you add javascript to zeppelin paragraph, then you  need at drilldown library as well. Check the updated doc [Use in Zeppelin](https://github.com/knockdata/spark-highcharts/blob/master/docs/UseInZeppelin.md)

**Comment by HarvinderBhullar** [comment]
Thanks you so much. It worked, I was not adding the drill down library.
