### ISSUE TITLE
Is it possible to use it from jdbc interpreter in zeppelin ? 

### ISSUE THREAD

**Issue by shishircc** [knockdata/spark-highcharts#16]

**Comment by rockiey** [comment]
It can be used with Spark JDBC driver. [jdbc-to-other-databases](http://spark.apache.org/docs/latest/sql-programming-guide.html#jdbc-to-other-databases)

Not directly with jdbc interpreter.

**Comment by shishircc** [comment]
Thanks  ! I am using this library to analyse some data inside solr. 
I am also interested in supporting highstock with this library. (http://www.highcharts.com/stock/demo) 

I will send a PR once done (I have to undersand how this works first :) ).

**Comment by rockiey** [comment]
It will be great if you can have a PR for highstock. Thanks
