### ISSUE TITLE
zeppelin 0.6.2 but not showing any graphs

### ISSUE THREAD

**Issue by mmrezaie** [knockdata/spark-highcharts#17]
Hi,

I have used the docker and spark-highchart plots everything fine, but when I use my own spark-2.0.0 and spark-highchart 0.6.2 although it says it finished and the output of the zeppelin cell grows, but I cannot see any chart. The same code works fine with the docker! I was wondering if it is because of zeppelin or spark versions?

**Comment by rockiey** [comment]
Do you means https://hub.docker.com/r/knockdata/zeppelin-highcharts/?

**Comment by mmrezaie** [comment]
Yes for the docker, but for the one that doesn't work is just the spark binary from the website, and zeppelin also from the zeppelin website. Although now I looked at your Dockerfile configs and did the same steps and now I have my own functioning zeppelin that shows the charts, but I wonder since you are doing some additions to the zeppelin before compiling it in the docker, can they be what I was missing.

`sed -i 's/"angular":/"highcharts": "^4.2.6","angular":/' /tmp/zeppelin/zeppelin-web/bower.json \
 sed -i 's#"highlightjs": {#"highcharts": {"main": ["highcharts.js","highcharts-more.js","modules/exporting.js","modules/drilldown.js","modules/maps.js"]},"highlightjs": {#' /tmp/zeppelin/zeppelin-web/bower.json \
  xmlstarlet ed -s /_:project/_:dependencies -t elem -n dependency -v spark-highcharts /tmp/zeppelin/spark-dependencies/pom.xml > pom2.xml \
  sed -i "s:spark-highcharts:<groupId>com.knockdata</groupId><artifactId>spark-highcharts</artifactId><version>$SPARK_HIGHCHART_VERSION</version>:" pom2.xml \
`

I thought I did the same by adding the JS inside my zeppelin notebook, and in the configuration for my spark interpreter.

**Comment by rockie-yang** [comment]
Yes. in the docker file, I added highcharts.js and spark-highcharts lib. 

If you want use for your existing Zeppelin, you can follow [Use in Zeppelin](https://github.com/knockdata/spark-highcharts/blob/master/docs/UseInZeppelin.md)
It might be tricky to debug if something goes wrong. You can check the browser debug function if there are some error logs.

**Comment by mmrezaie** [comment]
Thanks, I had done all those but I will test some other stuff. I am using bleeding edge - master branch - of spark and zeppelin. So they might be the problem. I will test them and report.
