### ISSUE TITLE
Heatmap Example

### ISSUE THREAD

**Issue by HarvinderBhullar** [knockdata/spark-highcharts#19]
Hi

Your work has made lot of enhancement to Zeppelin and and Zeppelin more appealing to business users. 

How to create Heatmap? I could not find any example.

**Comment by rockie-yang** [comment]
Thanks.

I have added [heatmap demos](https://github.com/knockdata/spark-highcharts/blob/master/docs/DemoHeatmap.md#heatmap-demo)
