### ISSUE TITLE
Drilldown with different chart type

### ISSUE THREAD

**Issue by ArslanSaleem** [knockdata/spark-highcharts#22]
Hi @rockie-yang,
Does spark-highcharts have feature to drilldown into different chart type and different data source/dataframe?
I had seen the drilldown example but i didn't find any yet, further does this api has Zoom feature of highcharts? 
Or is there any way to add such features?

**Comment by rockie-yang** [comment]
Thanks very much for trying spark-highcharts. It support zoom and drilldown on different types.

For zoom please check 
https://github.com/knockdata/spark-highcharts/blob/b30da28624ad22c612bb647efa4999c847f28cd6/docs/DemoLineChart.md#line-chart-zoomable

For drilldown, check the following example

        val chart: Highcharts = highcharts(
              bank.series(
                "name" -> "marital",
                "y" -> avg(col("balance")))
                  .drilldown("name" -> "job",
                "y" -> avg(col("balance"))).set("type", "column")
                  .drilldown("name" -> "education",
                "y" -> avg(col("balance"))))
        chart.plot

**Comment by ArslanSaleem** [comment]
Thanks @rockie-yang excellent work.
