### ISSUE TITLE
Multiple Charts in Plot

### ISSUE THREAD

**Issue by lmendes1302** [knockdata/spark-highcharts#32]
Hi!

There is any way to make two plots in the same canvas? For example: I want to do a scatterplot + error bars. Something like this: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-errorbar/on-scatter/

Thanks

**Comment by rockie-yang** [comment]
What are the version of Zeppelin & Spark?
can you also share the spark-highcharts code you are using

**Comment by lmendes1302** [comment]
Zeppelin version 0.7.1
spark 2.2.0

Snippet code

highcharts(testDataAvgTicket.union(controlDataAvgTicket)
      .seriesCol("group")
      .series("x" -> "dayOfMonth", "low" -> "low", "q1"->"Q1", "median" -> "median", "q3" -> "Q3", "high"->"high")
      .series("x" -> "dayOfMonth", "y" -> "avgAmount", "low" -> "low", "high" -> "high")
      .orderBy(col("dayOfMonth"))
  )
  .chart(Chart.errorbar)
  .chart(Chart.line)
  .plotOptions(PlotOptions.errorbar)
  .title("Title")
  .xAxis(XAxis("Date"))
  .yAxis(YAxis("Spending"))
  .plot()

Thanks for all the help!

**Comment by rockie-yang** [comment]
It's a bit different. Please check the test case, https://github.com/knockdata/spark-highcharts/blob/master/src/test/scala/com/knockdata/spark/highcharts/demo/DemoComboChart.scala

**Comment by lmendes1302** [comment]
It worked! Thanks!
